export const ADD_TILE = "ADD_TILE";
export const SELECT_TILE = "SELECT_TILE";
export const CLOSE_TILE = "CLOSE_TILE";

export const FETCH_BOOTSTRAP = "FETCH_BOOTSTRAP";
export const RECEIVE_BOOTSTRAP_SUCCESS = "RECEIVE_BOOTSTRAP_SUCCESS";
export const RECEIVE_BOOTSTRAP_ERROR = "RECEIVE_BOOTSTRAP_ERROR";

export const FETCH_RASTER = "FETCH_RASTER";
export const RECEIVE_RASTER = "RECEIVE_RASTER";
export const REMOVE_RASTER = "REMOVE_RASTER";
