export const ADD_TILE = "ADD_TILE";
export const SELECT_TILE = "SELECT_TILE";
export const CLOSE_TILE = "CLOSE_TILE";

export const FETCH_BOOTSTRAP = "FETCH_BOOTSTRAP";
export const RECEIVE_BOOTSTRAP_SUCCESS = "RECEIVE_BOOTSTRAP_SUCCESS";
export const RECEIVE_BOOTSTRAP_ERROR = "RECEIVE_BOOTSTRAP_ERROR";

export const FETCH_RASTER = "FETCH_RASTER";
export const RECEIVE_RASTER = "RECEIVE_RASTER";
export const REMOVE_RASTER = "REMOVE_RASTER";

export const ADD_ASSET = "ADD_ASSET";

export const ADD_TIMESERIES = "ADD_TIMESERIES";

export const FETCH_LEGEND = "FETCH_LEGEND";
export const ADD_LEGEND = "ADD_LEGEND";
